# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{bio-genomic-file}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["timpalpant"]
  s.date = %q{2011-07-05}
  s.description = %q{Allows iteration and querying of common genomic file formats, including Bed, BedGraph, GFF, Wiggle, and SAM/BAM}
  s.email = %q{tim@palpant.us}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bio-genomic-file.gemspec",
    "lib/bio-genomic-file.rb",
    "lib/bio/db/affy.rb",
    "lib/bio/db/assembly.rb",
    "lib/bio/db/bed.rb",
    "lib/bio/db/bedgraph.rb",
    "lib/bio/db/entry_file.rb",
    "lib/bio/db/entry_file_sniffer.rb",
    "lib/bio/db/genome.rb",
    "lib/bio/db/gff.rb",
    "lib/bio/db/macs.rb",
    "lib/bio/db/nucleosome.rb",
    "lib/bio/db/pwm.rb",
    "lib/bio/db/read_file.rb",
    "lib/bio/db/sam.rb",
    "lib/bio/db/spot_file.rb",
    "lib/bio/db/wig.rb",
    "lib/bio/db/wig_math.rb",
    "lib/bio/genomics/contig.rb",
    "lib/bio/genomics/genomic_data.rb",
    "lib/bio/genomics/genomic_index_error.rb",
    "lib/bio/genomics/genomic_interval.rb",
    "lib/bio/genomics/read.rb",
    "lib/bio/genomics/sparse_array.rb",
    "lib/bio/genomics/spot.rb",
    "lib/bio/stats.rb",
    "lib/bio/utils/fixed_precision.rb",
    "lib/bio/utils/parallelizer.rb",
    "lib/bio/utils/tabix.rb",
    "lib/bio/utils/ucsc_tools.rb",
    "lib/bio/utils/unix_file_utils.rb",
    "spec/affy_spec.rb",
    "spec/assembly_spec.rb",
    "spec/bed_spec.rb",
    "spec/bedgraph_spec.rb",
    "spec/contig_spec.rb",
    "spec/fixed_precision_spec.rb",
    "spec/fixtures/test.2bit",
    "spec/fixtures/test.affy",
    "spec/fixtures/test.bam",
    "spec/fixtures/test.bed",
    "spec/fixtures/test.bedGraph",
    "spec/fixtures/test.bw",
    "spec/fixtures/test.fa",
    "spec/fixtures/test.file1",
    "spec/fixtures/test.file2",
    "spec/fixtures/test.file3",
    "spec/fixtures/test.gff",
    "spec/fixtures/test.len",
    "spec/fixtures/test.macs",
    "spec/fixtures/test.nukes",
    "spec/fixtures/test.sam",
    "spec/fixtures/test.wig",
    "spec/genome_spec.rb",
    "spec/genomic_data_spec.rb",
    "spec/genomic_interval_spec.rb",
    "spec/gff_spec.rb",
    "spec/macs_spec.rb",
    "spec/nucleosome_spec.rb",
    "spec/parallelizer_spec.rb",
    "spec/read_spec.rb",
    "spec/sam_spec.rb",
    "spec/sparse_array_spec.rb",
    "spec/spec_helper.rb",
    "spec/spot_spec.rb",
    "spec/stats_spec.rb",
    "spec/ucsc_tools_spec.rb",
    "spec/unix_file_utils_spec.rb",
    "spec/wig_spec.rb"
  ]
  s.homepage = %q{http://github.com/timpalpant/bio-genomic-file}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Work with genomic file formats in a consistent, simple and performant fashion}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<bio>, [">= 1.4.0"])
      s.add_runtime_dependency(%q<parallel-forkmanager>, ["~> 1.5.1"])
      s.add_development_dependency(%q<rspec>, ["~> 2.6.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.2"])
    else
      s.add_dependency(%q<bio>, [">= 1.4.0"])
      s.add_dependency(%q<parallel-forkmanager>, ["~> 1.5.1"])
      s.add_dependency(%q<rspec>, ["~> 2.6.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.2"])
    end
  else
    s.add_dependency(%q<bio>, [">= 1.4.0"])
    s.add_dependency(%q<parallel-forkmanager>, ["~> 1.5.1"])
    s.add_dependency(%q<rspec>, ["~> 2.6.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.2"])
  end
end

